### ISSUE TITLE
More verbose output?

### ISSUE THREAD

**Issue by acinader** [gogap/go-wkhtmltox#2]
Any way to get more verbose output?  Would be nice to see the standard out logged somewhere?

**Comment by xujinzheng** [comment]
you mean's the log of wkhtmltopdf command ?

**Comment by acinader** [comment]
Yes, the output from wkhtmltoimage

Really only needed for debug.

**Comment by xujinzheng** [comment]
I added the verbose to app.conf, and you could set `verbose = true` for print more debug info
https://github.com/gogap/go-wkhtmltox/blob/master/app.conf

you should pull `idocking/go-wkhtmltox:latest` for update docker image

**Comment by acinader** [comment]
thank you!
