### ISSUE TITLE
Issue in converting html to pdf

### ISSUE THREAD

**Issue by revathi-murali** [gogap/go-wkhtmltox#7]
I am using `go-wkhtmltox` package  as a library instead of  a service.  I currently see issues when I try to convert html to pdf (html to image is working fine).

**Sample Code**

```
htmlToX, err := wkhtmltox.New(conf)
fetcherOpts := wkhtmltox.FetcherOptions{}

var convertOpts wkhtmltox.ConvertOptions
convertOpts = &wkhtmltox.ToPDFOptions{URI: "https://google.com"}

convData, err := htmlToX.Convert(fetcherOpts, convertOpts)
```

**Error Details**

`open /var/folders/yb/xxxx/T/go-wkhtmltox539727929/79b4072e-e3ee-49a0-997d-e86ce49ab687.pdf: no such file or directory.` The error points to [this](https://github.com/gogap/go-wkhtmltox/blob/master/wkhtmltox/wkhtmltox.go#L334) line in the codebase.

Any idea on why the error is thrown? or am I missing something?

**Comment by xujinzheng** [comment]
can you show me your full code in `main.go` to reproduce the issue?

**Comment by revathi-murali** [comment]
@xujinzheng  Please refer [this gist](https://gist.github.com/revathi-murali/1df0d8cb9869915bc3f98a50ee8b0e63) for main.go

**Comment by xujinzheng** [comment]
This code is worked fine at my mac, what is your `wkhtmltopdf` 's version? 

```
wkhtmltopdf -V
wkhtmltopdf 0.12.3 (with patched qt)
```

**Comment by revathi-murali** [comment]
Its 0.12.5

```
wkhtmltopdf -V
wkhtmltopdf 0.12.5 (with patched qt)
```

**Comment by xujinzheng** [comment]
![image](https://user-images.githubusercontent.com/885569/50043506-3f6f1780-00b0-11e9-914f-5680250dfff7.png)

```
package main

import (
	"fmt"
	"github.com/gogap/config"
	"github.com/gogap/go-wkhtmltox/wkhtmltox"
	log "github.com/sirupsen/logrus"
)

func main() {

	conf := config.NewConfig(
		config.ConfigFile("wkhtml.conf"),
	)
	htmlToX, err := wkhtmltox.New(conf)
	fetcherOpts := wkhtmltox.FetcherOptions{}
	var convertOpts wkhtmltox.ConvertOptions
	convertOpts = &wkhtmltox.ToPDFOptions{URI: "https://google.com"}

	convData, err := htmlToX.Convert(fetcherOpts, convertOpts)
	if err != nil {
		log.Println("error in converting html to pdf")
		log.Println(err)
	}

	fmt.Println(string(convData))
}
```

**Comment by revathi-murali** [comment]
I tried running the above code and this is the error

![screen shot 2018-12-17 at 11 35 08 am](https://user-images.githubusercontent.com/2732287/50069530-82d09f80-01f0-11e9-83e2-fbd20dd74bcb.jpg)


I also tried with `0.12.3` version of wkhtmltopdf but still got the same error

**Comment by xujinzheng** [comment]
I think you should add some debug print info at

https://github.com/gogap/go-wkhtmltox/blob/master/wkhtmltox/wkhtmltox.go#L315

this line will execute command to generate pdf

**Comment by xujinzheng** [comment]
```go
output, err = execCommand(p.timeout, data, cmd, args...)

fmt.Println("output:",string(output))
fmt.Println("data:", string(data))
fmt.Println("cmd:", cmd)
fmt.Println("args:", args)
```

**Comment by revathi-murali** [comment]
Yeah already modified the code to check the same but no result. I have a question - Is there a way to specify the path of the `wkhtmltopdf` or `wkhtmltoimage` executable to wkhtmltox via conf? (although the path is added to the $PATH)

**Comment by xujinzheng** [comment]
Did not support this currently.

while you get the print info, you could execute the command in terminal.

cmd + args

**Comment by revathi-murali** [comment]
Okay thanks. Closing this issue.
